const mongoose = require('mongoose');

const consumer = mongoose.Schema({
  enq_type: String,
  pro_type: String,
  acc_type: String,
  number_app: Number,
  member: String,
  amount: Number,
  currency: String,
  scorecard: String,
  app_type: String,
  id_type: String,
  id_number: String,
  id_expire: Date,
  gender: String,
  marital_status: String,
  dob: Date,
  pob_prov: String,
  pob_dist: String,
  pob_comm: String,
  faname_eng: String,
  finame_eng: String,
  faname_khm: String,
  finame_khm: String,
  email_address: String,
  add_type: String,
  provice: String,
  district: String,
  commune: String,
  village: String,
  street: String,
  house: String,
  other_vill_eng: String,
  other_vill_khm: String,
  phone_number: String,
  country_code: String,
  phone_type: String,
  emp_type: String,
  emp_self: String,
  lenght: String,
  occupation: String,
  emp_name: String,
  salary: String,
  emp_currency: String,
  emp_add_type: String,
  emp_prov: String,
  emp_dist: String,
  emp_comm: String,
  emp_vill: String,
  emp_street: String,
  emp_house: String,
  empother_vill_eng: String,
  empother_vill_khm: String,
  created: Date,
  updated: Date
});

module.exports = mongoose.model('consumers', consumer);